version: "3.9"

services:
  python-api:
    build: ./python-api
    container_name: python-api
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - rabbitmq
      - blender
    volumes:
      - shared_data:/app/data   # Volumen compartido con Blender

  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  blender:
    build: ./blender-service
    container_name: blender
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - shared_data:/app/data   # Volumen compartido con Python API

volumes:
  rabbitmq_data:
  shared_data:   # Este volumen compartido permite que ambos contenedores lean/escriban archivos
