version: "3.9"

services:
  python-api:
    build: ./python-api
    container_name: python-api
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - rabbitmq
      - blender

  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # Conexión de apps (Java, Python, etc.)
      - "15672:15672" # Interfaz de administración
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  blender:
    build: ./blender-service
    container_name: blender
    ports:
      - "8080:8080"
    env_file:
      - .env

volumes:
  rabbitmq_data:
