version: "3.9"

services:
  python-api:
    build: ./python-api
    container_name: python-api
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - rabbitmq
      - blender
    volumes:
      - shared_data:/app/data
    deploy:
      resources:
        limits:
          memory: 300m
          cpus: "0.5"

  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
    deploy:
      resources:
        limits:
          memory: 300m
          cpus: "0.5"

  blender:
    build: ./blender-service
    container_name: blender
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - shared_data:/app/data
    deploy:
      resources:
        limits:
          memory: 350m
          cpus: "0.5"

volumes:
  rabbitmq_data:
  shared_data:
